[2025-05-04T06:20:48.927+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: csv_to_json.data_cleaning manual__2025-05-04T06:20:45.513494+00:00 [queued]>
[2025-05-04T06:20:48.931+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: csv_to_json.data_cleaning manual__2025-05-04T06:20:45.513494+00:00 [queued]>
[2025-05-04T06:20:48.932+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2025-05-04T06:20:48.932+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 1
[2025-05-04T06:20:48.932+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2025-05-04T06:20:48.938+0000] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): data_cleaning> on 2025-05-04 06:20:45.513494+00:00
[2025-05-04T06:20:48.941+0000] {standard_task_runner.py:52} INFO - Started process 188 to run task
[2025-05-04T06:20:48.943+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'csv_to_json', 'data_cleaning', 'manual__2025-05-04T06:20:45.513494+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/csv_to_json.py', '--cfg-path', '/tmp/tmpjs32jo4x', '--error-file', '/tmp/tmpctzlz24a']
[2025-05-04T06:20:48.945+0000] {standard_task_runner.py:80} INFO - Job 6: Subtask data_cleaning
[2025-05-04T06:20:48.980+0000] {task_command.py:371} INFO - Running <TaskInstance: csv_to_json.data_cleaning manual__2025-05-04T06:20:45.513494+00:00 [running]> on host d314c6c904e1
[2025-05-04T06:20:49.053+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=csv_to_json
AIRFLOW_CTX_TASK_ID=data_cleaning
AIRFLOW_CTX_EXECUTION_DATE=2025-05-04T06:20:45.513494+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-05-04T06:20:45.513494+00:00
[2025-05-04T06:20:49.085+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/csv_to_json.py", line 16, in dataCleaning
    df.dropna(inplace=True, ignore_index=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
TypeError: dropna() got an unexpected keyword argument 'ignore_index'
[2025-05-04T06:20:49.147+0000] {taskinstance.py:1412} INFO - Marking task as FAILED. dag_id=csv_to_json, task_id=data_cleaning, execution_date=20250504T062045, start_date=20250504T062048, end_date=20250504T062049
[2025-05-04T06:20:49.184+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 6 for task data_cleaning (dropna() got an unexpected keyword argument 'ignore_index'; 188)
[2025-05-04T06:20:49.252+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2025-05-04T06:20:49.342+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
