[2025-05-04T06:18:49.441+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: csv_to_json.data_cleaning manual__2025-05-04T06:18:46.961978+00:00 [queued]>
[2025-05-04T06:18:49.448+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: csv_to_json.data_cleaning manual__2025-05-04T06:18:46.961978+00:00 [queued]>
[2025-05-04T06:18:49.448+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2025-05-04T06:18:49.448+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 1
[2025-05-04T06:18:49.449+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2025-05-04T06:18:49.455+0000] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): data_cleaning> on 2025-05-04 06:18:46.961978+00:00
[2025-05-04T06:18:49.461+0000] {standard_task_runner.py:52} INFO - Started process 343 to run task
[2025-05-04T06:18:49.463+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'csv_to_json', 'data_cleaning', 'manual__2025-05-04T06:18:46.961978+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/csv_to_json.py', '--cfg-path', '/tmp/tmpfbuelg9r', '--error-file', '/tmp/tmp2zsy9cdz']
[2025-05-04T06:18:49.464+0000] {standard_task_runner.py:80} INFO - Job 3: Subtask data_cleaning
[2025-05-04T06:18:49.494+0000] {task_command.py:371} INFO - Running <TaskInstance: csv_to_json.data_cleaning manual__2025-05-04T06:18:46.961978+00:00 [running]> on host b724da555e81
[2025-05-04T06:18:49.528+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=csv_to_json
AIRFLOW_CTX_TASK_ID=data_cleaning
AIRFLOW_CTX_EXECUTION_DATE=2025-05-04T06:18:46.961978+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-05-04T06:18:46.961978+00:00
[2025-05-04T06:18:49.530+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/csv_to_json.py", line 11, in dataCleaning
    df = pd.read_csv('/opt/airflow/data/top-1000-trending-youtube-videos.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data/top-1000-trending-youtube-videos.csv'
[2025-05-04T06:18:49.535+0000] {taskinstance.py:1412} INFO - Marking task as FAILED. dag_id=csv_to_json, task_id=data_cleaning, execution_date=20250504T061846, start_date=20250504T061849, end_date=20250504T061849
[2025-05-04T06:18:49.539+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 3 for task data_cleaning ([Errno 2] No such file or directory: '/opt/airflow/data/top-1000-trending-youtube-videos.csv'; 343)
[2025-05-04T06:18:49.561+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2025-05-04T06:18:49.584+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
